apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ dxDamPersistenceStgRoPvcName }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeMode: Filesystem
  storageClassName: "{{ dxDamPersistenceRoStorageClassName }}"
