kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: "{{ dxDamPersistenceStorageClassName }}"
  annotations:
    description: Storage class for DAM persistence storage
  managedFields:
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
