apiVersion: v1
kind: ConfigMap
metadata:
  name: dx-deployment
  namespace: "dx"
data:
  dx.deploy.dam.enabled: "true"
  dx.deploy.dam.operator.image: "dx/digital-asset-management-operator"
  dx.deploy.dam.operator.tag: "v95_CF191_20201211-2152"
  dx.deploy.dam.persistence.image: "dx/postgres"
  dx.deploy.dam.persistence.tag: "v1.5.0_20201211-2155"
  dx.deploy.dam.volume: "dx-dam-pv"
  dx.deploy.dam.imgprocessor.image: "dx/image-processor"
  dx.deploy.dam.imgprocessor.tag: "v1.5.0_20201211-2154"
  dx.deploy.dam.storageclass: "dx-deploy-stg"
  dx.deploy.dam.image: "dx/digital-asset-manager"
  dx.deploy.dam.tag: "v1.5.0_20201211-2155"
  dx.deploy.contentui.enabled: "true"
  dx.deploy.contentui.image: "dx/content-composer"
  dx.deploy.contentui.tag: "v1.5.0_20201211-2151"
  dx.deploy.experienceapi.enabled: "true"
  dx.deploy.experienceapi.image: "dx/ringapi"
  dx.deploy.experienceapi.tag: "v1.5.0_20201211-2200"
  # LDAP administrator username is dx_user,
  dx.deploy.openldap.enabled: "false"
  dx.deploy.openldap.image: "dx/openldap"
  dx.deploy.openldap.tag: "v1.0.0-master_20201212_1607741365"
  dx.deploy.openldap.suffix: "dc=ocp00,dc=os,dc=hhue"
  dx.deploy.openldap.country: "AT"
  dx.deploy.openldap.pwd: "start123."
  dx.deploy.openldap.org: "2i"
