kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: "{{ dxProfileStorageClassName }}"
  annotations:
    description: "{{ dxProfileStorageClassName }}"
  managedFields:
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
