apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ dxDamPersistenceStgPvName }}"
spec:
  capacity:
    storage: "{{ dxDamPersistenceStgCapacity }}"
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "{{ dxDamPersistenceStgNfsExport }}"
    server: "{{ dxDamPersistenceStgNfsServer }}"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "{{ dxDamPersistenceStorageClassName }}"
