apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ dxDamPersistenceStgRoPvName }}"
spec:
  capacity:
    storage: "{{ dxDamPersistenceRoStgCapacity }}"
  accessModes:
    - ReadWriteOnce
  nfs:
    path: "{{ dxDamPersistenceRoStgNfsExport }}"
    server: "{{ dxDamPersistenceRoStgNfsServer }}"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "{{ dxDamPersistenceRoStorageClassName }}"
