apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ dxDamPvcName }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: "{{ dxDamPvName }}"
