apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ dxDamPvName }}"
spec:
  capacity:
    storage: "{{ dxDamStgCapacity }}"
  accessModes:
    - ReadWriteMany
  nfs:
    path: "{{ dxDamStgNfsExport }}"
    server: "{{ dxDamStgNfsServer }}"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "{{ dxProfileStorageClassName }}"
