apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ imageRegistryPvcName }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 64Gi
  volumeName: "{{ imageRegistryPvName }}"
