apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ imageRegistryPvName }}"
spec:
  capacity:
    storage: "{{ imageRegistryCapacity }}"
  accessModes:
    - ReadWriteMany
  nfs:
    path: "{{ imageRegistryNfsExport }}"
    server: "{{ imageRegistryNfsServer }}"
  persistentVolumeReclaimPolicy: Retain
