apiVersion: v1
kind: Secret
data:
  ##
  ## base64 encoded password
  bindPassword: "{{ ldapAdminUserPwd | b64encode }}"
metadata:
  name: "{{ ldapBindSecretNameInOscp }}"
  namespace: openshift-config
