apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    description: "{{ dxThinRetainStgClassName }}"
  managedFields:
    - apiVersion: storage.k8s.io/v1
  name: "{{ dxThinRetainStgClassName }}"
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
