---
- name: Set the tmp directory for the backup files with default just once
  ansible.builtin.set_fact:
    __backup_temp_dir: "{{ backupFileDict['tmpDir'] | default('/tmp') }}"
  tags:
    - always

- name: Make sure the tmp directory for the backup ({{ __backup_temp_dir }}) exists
  kubernetes.core.k8s_exec:
    namespace: "{{ roleNs }}"
    host: "{{ roleHost }}"
    api_key: "{{ roleKey }}"
    command: "mkdir -p {{ __backup_temp_dir }}"
    pod: "{{ roleDamPodName }}"
    container: "{{ roleDamPodContainerName }}"
    validate_certs: "no"
  register: podResult
  failed_when: (podResult.rc != 0)
  tags:
    - always

- name: Set the default tar command to be non-verbose
  ansible.builtin.set_fact:
    backup_command: "tar -cpzf"
  tags:
    - always

- name: Set the default tar command to be verbose if requested
  ansible.builtin.set_fact:
    backup_command: "tar -cvpzf"
  when: ((backupFileDict['verbose'] is defined) and
    ( backupFileDict['verbose'] == true))
  tags:
    - always

- name: Template the backup scripts
  ansible.builtin.include_tasks: templateAndCopyOneFile.yaml
  vars:
    __srcTemplate: "{{ __backupTemplate.j2 }}"
    __targetFile: "{{ __backupTemplate.sh }}"
  loop: "{{ backupTemplates }}"
  loop_control:
    loop_var: __backupTemplate
  tags:
    - always

- name: Start creating the backup file for directory {{ backupFileDict['name'] }} in the background
  kubernetes.core.k8s_exec:
    namespace: "{{ roleNs }}"
    host: "{{ roleHost }}"
    api_key: "{{ roleKey }}"
    command: "bash -c '{{ __backup_temp_dir }}/{{ backupTemplates[0].sh }} >/dev/null 2>/dev/null'"
    pod: "{{ roleDamPodName }}"
    container: "{{ roleDamPodContainerName }}"
  register: podResult
  failed_when: (podResult.rc != 0)
  tags:
    - always

- name: Check if the backup has finished
  kubernetes.core.k8s_exec:
    namespace: "{{ roleNs }}"
    host: "{{ roleHost }}"
    api_key: "{{ roleKey }}"
    command: "{{ __backup_temp_dir }}/{{ backupTemplates[1].sh }}"
    pod: "{{ roleDamPodName }}"
    container: "{{ roleDamPodContainerName }}"
  register: podResult
  until: podResult is succeeded
  retries: "{{ checkNumberRetries | default('90') }}"
  delay: "{{ checkDelayBetweenRetries | default('20') }}"
  tags:
    - always

- name: Check if tar did complete successfully
  kubernetes.core.k8s_exec:
    namespace: "{{ roleNs }}"
    host: "{{ roleHost }}"
    api_key: "{{ roleKey }}"
    command: "{{ __backup_temp_dir }}/{{ backupTemplates[2].sh }}"
    pod: "{{ roleDamPodName }}"
    container: "{{ roleDamPodContainerName }}"
  register: podResult
  failed_when: (podResult.rc != 0)
  tags:
    - always
##
## Log the files being backed up
- name: Log files being backed up
  ansible.builtin.debug:
    msg:
      - "Files being backed up:"
      - "{{ podResult.stdout_lines }}"
  when: ((backupFileDict['verbose'] is defined) and
    ( backupFileDict['verbose'] == true))
  tags:
    - always
