---
- name: Copy DAM backup file to {{ roleTargetDirectoryForBackupFiles }}/{{ item['backupFile'] }}_{{ roleBackupTimestamp }}.tar.gz
  ansible.builtin.command:
    argv:
      - "{{ oscpClientBin | default('/usr/local/bin/oc') }}"
      - "-n"
      - "{{ roleNs }}"
      - "cp"
      - "{{ roleDamPodName }}:/tmp/{{ backupFileDict['backupFile'] }}_{{ roleBackupTimestamp }}.tar.gz"
      - "{{ roleTargetDirectoryForBackupFiles }}/{{ backupFileDict['backupFile'] }}_{{ roleBackupTimestamp }}.tar.gz"
  register: cmdResult
  failed_when: (cmdResult.rc != 0)
  tags:
    - always

- name: Delete the backup file on the pod
  kubernetes.core.k8s_exec:
    namespace: "{{ roleNs }}"
    host: "{{ roleHost }}"
    api_key: "{{ roleKey }}"
    command: "rm -f /tmp/{{ backupFileDict['backupFile'] }}_{{ roleBackupTimestamp }}.tar.gz"
    pod: "{{ roleDamPodName }}"
    validate_certs: "no"
  register: podResult
  failed_when: (podResult.rc != 0)
  tags:
    - always
