---
- name: Set the tmp directory for the backup files with default just once
  ansible.builtin.set_fact:
    __backup_temp_dir: "{{ backupFileDict['tmpDir'] | default('/tmp') }}"
  tags:
    - always

- name: Copy DAM backup file to {{ roleTargetDirectoryForBackupFiles }}/{{ item['backupFile'] }}_{{ roleBackupTimestamp }}.tar.gz
  ansible.builtin.command:
    argv:
      - "{{ oscpClientBin | default('/usr/local/bin/oc') }}"
      - "--token={{ roleKey }}"
      - "--server={{ roleHost }}"
      - "-n"
      - "{{ roleNs }}"
      - "cp"
      - "{{ roleDamPodName }}:{{ __backup_temp_dir }}/{{ backupFileDict['backupFile'] }}_{{ roleBackupTimestamp }}.tar.gz"
      - "{{ roleTargetDirectoryForBackupFiles }}/{{ backupFileDict['backupFile'] }}_{{ roleBackupTimestamp }}.tar.gz"
      - "-c"
      - "{{ roleDamPodContainerName }}"
  register: cmdResult
  failed_when: (cmdResult.rc != 0)
  tags:
    - always

- name: Delete the backup file on the pod
  kubernetes.core.k8s_exec:
    namespace: "{{ roleNs }}"
    host: "{{ roleHost }}"
    api_key: "{{ roleKey }}"
    command: "rm -f {{ __backup_temp_dir }}/{{ backupFileDict['backupFile'] }}_{{ roleBackupTimestamp }}.tar.gz"
    pod: "{{ roleDamPodName }}"
    container: "{{ roleDamPodContainerName }}"
    validate_certs: "no"
  register: podResult
  failed_when: (podResult.rc != 0)
  tags:
    - always

- name: Link the lastest version to the current backup file
  ansible.builtin.shell: |
    rm -rf {{ roleTargetDirectoryForBackupFiles }}/{{ backupFileDict['backupFile'] }}_{{ roleLatestLinkSuffix }}.tar.gz
    ln {{ roleTargetDirectoryForBackupFiles }}/{{ backupFileDict['backupFile'] }}_{{ roleBackupTimestamp }}.tar.gz {{ roleTargetDirectoryForBackupFiles }}/{{ backupFileDict['backupFile'] }}_{{ roleLatestLinkSuffix }}.tar.gz
  register: shellResult
  failed_when: (shellResult.rc != 0)
  tags:
    - always
