---
- name: Template and copy a file to the pod
  block:
    - name: Create temporary directory for templating
      ansible.builtin.tempfile:
        state: directory
        prefix: backupScript
      register: __backupScript
      tags:
        - always

    - name: Template file {{ __srcTemplate }} writing to {{ __targetFile }}
      ansible.builtin.template:
        src: "{{ __srcTemplate }}"
        dest: "{{ __backupScript.path }}/{{ __targetFile }}"
        mode: "755"
      tags:
        - always

    - name: Copy the file {{ __targetFile }} to the pod
      kubernetes.core.k8s_cp:
        namespace: "{{ roleNs }}"
        host: "{{ roleHost }}"
        api_key: "{{ roleKey }}"
        local_path: "{{ __backupScript.path }}/{{ __targetFile }}"
        remote_path: "{{ backupFileDict['tmpDir'] | default('/tmp') }}/{{ __targetFile }}"
        pod: "{{ roleDamPodName }}"
        no_preserve: false
      tags:
        - always

  always:
    - name: Cleanup temporary directory for templating
      ansible.builtin.file:
        state: absent
        path: "{{ __backupScript.path }}"
