---
- name: Make sure we have the latest version of the davfs2 package installed
  become_user: "root"
  ansible.builtin.yum:
    name: davfs2
    state: latest
  tags:
    - always

- name: Add credentials to /etc/davfs2/secrets
  become_user: "root"
  ansible.builtin.blockinfile:
    path: "/etc/davfs2/secrets"
    block: |
      {{ mountpoint.path }} {{ roleWpsAdminUser }} {{ roleWpsAdminPassword }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ roleWpsAdminUser }}"
    state: present
  tags:
    - always

- name: Set the option to immediately upload files to the server
  become_user: "root"
  ansible.builtin.blockinfile:
    path: "/etc/davfs2/davfs2.conf"
    block: |
      delay_upload 0
    marker: "# {mark} ANSIBLE MANAGED BLOCK delay_upload"
    state: present
  tags:
    - always

- name: Mount the WebDav filesystem {{ roleWebDavHostUrl }}/{{ webDavItem.webDavMountDir }}/
  become_user: "root"
  ansible.builtin.command:
    argv:
      - "mount"
      - "-t"
      - "davfs"
      - "-o"
      - "noexec"
      - "{{ roleWebDavHostUrl }}/{{ webDavItem.webDavMountDir }}/"
      - "{{ mountpoint.path }}"
  register: cmdResult
  tags:
    - always
