---
- name: Copy DB backup file {{ backupFileDict['tmpDir'] | default('/tmp') }}/{{ backupFileDict['name'] }}_{{ roleBackupTimestamp }}.dmp.gz to {{ roleTargetDirectoryForBackupFiles }}/{{ backupFileDict['backupFile'] }}_{{ roleBackupTimestamp }}.dmp.gz
  ansible.builtin.command:
    argv:
      - "{{ oscpClientBin | default('/usr/local/bin/oc') }}"
      - "-n"
      - "{{ roleNs }}"
      - "cp"
      - "-c"
      - "{{ rolePersistentPodContainerName }}"
      - "{{ rolePersistentPodName }}:{{ backupFileDict['tmpDir'] | default('/tmp') }}/{{ backupFileDict['backupFile'] }}_{{ roleBackupTimestamp }}.dmp.gz"
      - "{{ roleTargetDirectoryForBackupFiles }}/{{ backupFileDict['backupFile'] }}_{{ roleBackupTimestamp }}.dmp.gz"
  register: cmdResult
  failed_when: (cmdResult.rc != 0)
  tags:
    - always

- name: Delete the backup file on the pod
  kubernetes.core.k8s_exec:
    namespace: "{{ roleNs }}"
    host: "{{ roleHost }}"
    api_key: "{{ roleKey }}"
    command: "rm -f {{ backupFileDict['tmpDir'] | default('/tmp') }}/{{ backupFileDict['backupFile'] }}_{{ roleBackupTimestamp }}.dmp.gz"
    pod: "{{ rolePersistentPodName }}"
    container: "{{ rolePersistentPodContainerName }}"
  register: podResult
  failed_when: (podResult.rc != 0)
  tags:
    - always
