---
- name: Set the tmp directory for the backup files with default just once
  ansible.builtin.set_fact:
    __backup_temp_dir: "{{ backupFileDict['tmpDir'] | default('/tmp') }}"
  tags:
    - always

- name: Copy DB backup file {{ __backup_temp_dir }}/{{ backupFileDict['name'] }}_{{ roleBackupType }}_{{ roleBackupTimestamp }}.dmp.gz to {{ roleTargetDirectoryForBackupFiles }}/{{ backupFileDict['backupFile'] }}_{{ roleBackupType }}_{{ roleBackupTimestamp }}.dmp.gz
  ansible.builtin.command:
    argv:
      - "{{ oscpClientBin | default('/usr/local/bin/oc') }}"
      - "-n"
      - "{{ roleNs }}"
      - "cp"
      - "-c"
      - "{{ rolePersistentPodContainerName }}"
      - "{{ rolePersistentPodName }}:{{ __backup_temp_dir }}/{{ backupFileDict['backupFile'] }}_{{ roleBackupType }}_{{ roleBackupTimestamp }}.dmp.gz"
      - "{{ roleTargetDirectoryForBackupFiles }}/{{ backupFileDict['backupFile'] }}_{{ roleBackupType }}_{{ roleBackupTimestamp }}.dmp.gz"
  register: cmdResult
  failed_when: (cmdResult.rc != 0)
  tags:
    - always

- name: Delete the backup file on the pod
  kubernetes.core.k8s_exec:
    namespace: "{{ roleNs }}"
    host: "{{ roleHost }}"
    api_key: "{{ roleKey }}"
    command: "rm -f {{ __backup_temp_dir }}/{{ backupFileDict['backupFile'] }}_{{ roleBackupType }}_{{ roleBackupTimestamp }}.dmp.gz"
    pod: "{{ rolePersistentPodName }}"
    container: "{{ rolePersistentPodContainerName }}"
  register: podResult
  failed_when: (podResult.rc != 0)
  tags:
    - always

- name: Link the lastest version to the current backup file
  ansible.builtin.shell: |
    rm -rf {{ roleTargetDirectoryForBackupFiles }}/{{ backupFileDict['backupFile'] }}_{{ roleBackupType }}_{{ roleLatestLinkSuffix }}.dmp.gz
    ln {{ roleTargetDirectoryForBackupFiles }}/{{ backupFileDict['backupFile'] }}_{{ roleBackupType }}_{{ roleBackupTimestamp }}.dmp.gz {{ roleTargetDirectoryForBackupFiles }}/{{ backupFileDict['backupFile'] }}_{{ roleBackupType }}_{{ roleLatestLinkSuffix }}.dmp.gz
  register: shellResult
  failed_when: (shellResult.rc != 0)
  tags:
    - always
