---
##
## CHeck if the file to restore existis
- name: Check that the somefile.conf exists
  stat:
    path: "{{ targetDirectoryForBackupFiles }}/{{ fileToCheck['backupFile'] }}"
  register: stat_result
  tags:
    - always
##
## Fail if the file does not exit
- name: Fail if file is missing
  ansible.builtin.fail:
    msg: "File {{ targetDirectoryForBackupFiles }}/{{ fileToCheck['backupFile'] }} does not exist! Failing ..."
  when: (not stat_result.stat.exists)
  tags:
    - always
