---
# tasks file for getActiveDbPod to determine the active postgress database pod.
#
# Sets the following fact:
# -activePersistentPodName
###############################################################################
##
## Determine the currently active postgress pod
- name: Determine the active postgress database node
  kubernetes.core.k8s_exec:
    namespace: "{{ roleNs }}"
    host: "{{ roleHost }}"
    api_key: "{{ roleKey }}"
    command: "repmgr cluster show --compact --terse"
    pod: "{{ roleInitialPersistentPodName }}"
    container: "{{ rolePersistentPodContainerName }}"
  register: podResult
  failed_when: (podResult.rc != 0)
  tags:
    - always
##
## Get the name of the primary pod from the registered output as k8s_exec seems to have issues with cascaded commands
- name: Extract the name of the primary pod from the registered output
  shell: 'echo "{{ podResult.stdout }}" | grep " primary " | awk ''{split($0,a,"|"); print a[2]}'' | xargs'
  register: cmdResult
  tags:
    - always
##
## Retrieve the name of the active database pod
- name: Retrieve the name of the active database pod
  ansible.builtin.set_fact:
    activePersistentPodName: "{{ cmdResult.stdout }}"
  tags:
    - always
