---
- name: Execute SQL statements on pod {{ rolePod }}
  kubernetes.core.k8s_exec:
    namespace: "{{ roleNs }}"
    host: "{{ roleHost }}"
    api_key: "{{ roleKey }}"
    command: 'psql -d {{ roleDB }} -c "{{ roleSqlStatement }}"'
    pod: "{{ rolePod }}"
    container: "{{ roleContainer }}"
  register: podResult
  failed_when: (podResult.rc != 0)
  tags:
    - always

- name: SQL Result for Statement| "{{ roleSqlStatement }}"
  vars:
  ansible.builtin.debug:
    msg: "{{ '%s'| format(podResult.stdout) }}"
