---
- name: Set the tmp directory for the backup files with default just once
  ansible.builtin.set_fact:
    __backup_temp_dir: "{{ backupFileDict['tmpDir'] | default('/tmp') }}"
  tags:
    - always

- name: Make sure the tmp directory for the backup ({{ __backup_temp_dir }}) exists
  kubernetes.core.k8s_exec:
    namespace: "{{ roleNs }}"
    host: "{{ roleHost }}"
    api_key: "{{ roleKey }}"
    command: "mkdir -p {{ __backup_temp_dir }}"
    pod: "{{ roleDamPodName }}"
    container: "{{ roleDamPodContainerName }}"
    validate_certs: "no"
  register: podResult
  failed_when: (podResult.rc != 0)
  tags:
    - always

##
## Copy DAM backup files from local directory to the target pod
- name: Copy DAM backup files {{ backupFileDict['backupFile'] }} from {{targetDirectoryForBackupFiles}} to the target pod
  ansible.builtin.command:
    argv:
      - "{{ oscpClientBin | default('/usr/local/bin/oc') }}"
      - "--token={{ roleKey }}"
      - "--server={{ roleHost }}"
      - "-n"
      - "{{ roleNs }}"
      - "cp"
      - "{{roleTargetDirectoryForBackupFiles}}/{{ backupFileDict['backupFile'] }}"
      - "{{ roleDamPodName }}:{{ __backup_temp_dir }}/{{ backupFileDict['backupFile'] }}"
      - "-c"
      - "{{ roleDamPodContainerName }}"
  register: cmdResult
  failed_when: (cmdResult.rc != 0)
  tags:
    - always
