---
- name: Make sure the tmp directory for the backup ({{ backupFileDict['tmpDir'] | default('/tmp') }}) exists
  kubernetes.core.k8s_exec:
    namespace: "{{ roleNs }}"
    host: "{{ roleHost }}"
    api_key: "{{ roleKey }}"
    command: "mkdir -p {{ backupFileDict['tmpDir'] | default('/tmp') }}"
    pod: "{{ roleDamPodName }}"
    container: "{{ roleDamPodContainerName }}"
    validate_certs: "no"
  register: podResult
  failed_when: (podResult.rc != 0)
  tags:
    - always

##
## Copy DAM backup files from local directory to the target pod
- name: Copy DAM backup files {{ backupFileDict['backupFile'] }} from {{targetDirectoryForBackupFiles}} to the target pod
  ansible.builtin.command:
    argv:
      - "{{ oscpClientBin | default('/usr/local/bin/oc') }}"
      - "-n"
      - "{{ roleNs }}"
      - "cp"
      - "{{roleTargetDirectoryForBackupFiles}}/{{ backupFileDict['backupFile'] }}"
      - "{{ roleDamPodName }}:{{ backupFileDict['tmpDir'] | default('/tmp') }}/{{ backupFileDict['backupFile'] }}"
      - "-c"
      - "{{ roleDamPodContainerName }}"
  register: cmdResult
  failed_when: (cmdResult.rc != 0)
  tags:
    - always
