---
# tasks file for restoreDam
## Copy DAM backup files to local directory
- name: Copy DAM backup files from local directory to the target pod
  ansible.builtin.include_tasks: copyOneBackupFileToPod.yaml
  vars:
    backupFileDict: "{{ item }}"
  loop: "{{ roleDirectories }}"
  tags:
    - always
##
- name: Restore DAM backup files on target pod {{ roleDamPodName }} and container{{ roleDamPodContainerName }}
  ansible.builtin.include_tasks: restoreOneBackupFile.yaml
  vars:
    backupFileDict: "{{ item }}"
  loop: "{{ roleDirectories }}"
  tags:
    - always
##
## Echo the backup file name
- name: Echo the DAM restored file names
  ansible.builtin.debug:
    msg: "Restored file: {{ item['backupFile'] }} to {{ item['name'] }}"
  loop: "{{ roleDirectories }}"
  tags:
    - always
