---
- name: Set the tmp directory for the backup files with default just once
  ansible.builtin.set_fact:
    __backup_temp_dir: "{{ backupFileDict['tmpDir'] | default('/tmp') }}"
  tags:
    - always

- name: Template and copy a file to the pod
  block:
    - name: Create temporary directory for templating
      ansible.builtin.tempfile:
        state: directory
        prefix: restoreScript
      register: __restoreScript
      tags:
        - always

    - name: Template file {{ __srcTemplate }} writing to {{ __targetFile }}
      ansible.builtin.template:
        src: "{{ __srcTemplate }}"
        dest: "{{ __restoreScript.path }}/{{ __targetFile }}"
        mode: "755"
      tags:
        - always

    - name: Copy the file {{ __targetFile }} to the pod
      kubernetes.core.k8s_cp:
        namespace: "{{ roleNs }}"
        host: "{{ roleHost }}"
        api_key: "{{ roleKey }}"
        local_path: "{{ __restoreScript.path }}/{{ __targetFile }}"
        remote_path: "{{ __backup_temp_dir }}/{{ __targetFile }}"
        pod: "{{ roleDamPodName }}"
        container: "{{ roleDamPodContainerName }}"
        no_preserve: false
      tags:
        - always

  always:
    - name: Cleanup temporary directory for templating
      ansible.builtin.file:
        state: absent
        path: "{{ __restoreScript.path }}"
