---
- name: Make sure the tmp directory for the backup ({{ backupFileDict['tmpDir'] | default('/tmp') }}) exists
  kubernetes.core.k8s_exec:
    namespace: "{{ roleNs }}"
    host: "{{ roleHost }}"
    api_key: "{{ roleKey }}"
    command: "mkdir -p {{ backupFileDict['tmpDir'] | default('/tmp') }}"
    pod: "{{ rolePersistentPodName }}"
    container: "{{ rolePersistentPodContainerName }}"
  register: podResult
  failed_when: (podResult.rc != 0)
  tags:
    - always

##
## Copy DB backup files to the target pod
- name: Copy DB backup files to target pod {{ rolePersistentPodName }}
  ansible.builtin.command:
    argv:
      - "{{ oscpClientBin | default('/usr/local/bin/oc') }}"
      - "-n"
      - "{{ roleNs }}"
      - "cp"
      - "-c"
      - "{{ rolePersistentPodContainerName }}"
      - "{{ roleTargetDirectoryForBackupFiles }}/{{ backupFileDict['backupFile'] }}"
      - "{{ rolePersistentPodName }}:{{ backupFileDict['tmpDir'] | default('/tmp') }}/{{ backupFileDict['backupFile'] }}"
  register: cmdResult
  failed_when: (cmdResult.rc != 0)
  tags:
    - always
