---
##
## Copy DB backup files to the target pod
- name: Copy DB backup files to target pod {{ rolePersistentPodName }}
  ansible.builtin.include_tasks: copyOneBackupFileToPod.yaml
  vars:
    backupFileDict: "{{ item }}"
  loop: "{{ roleDatabases }}"
  tags:
    - always
##
## Restore databases to target pod
- name: Restore databases to target pod {{ rolePersistentPodName }}
  ansible.builtin.include_tasks: restoreOneDatabase.yaml
  vars:
    backupFileDict: "{{ item }}"
  loop: "{{ roleDatabases }}"
  tags:
    - always
##
## Echo the backup file name
- name: Echo the Postgress restored file names
  ansible.builtin.debug:
    msg: "Restored file: {{ item['backupFile'] }} to {{ item['name'] }}"
  loop: "{{ roleDatabases }}"
  tags:
    - always
