---
#####################################################################################
## Role to run xmlaccess.sh on the pod
#####################################################################################
- name: Run the XMLACCESS imports
  ansible.builtin.include_tasks: runOneXmlAccessFile.yml
  vars:
    itemXmlInputFile: "{{ propsItem }}"
  loop: "{{ roleXmlAccessImports }}"
  loop_control:
    loop_var: propsItem
  tags:
    - always
