---
#####################################################################################
## Role to run xmlaccess.sh on the pod
#####################################################################################
- name: Import XMLs from GitRepositories
  ansible.builtin.include_tasks: applyXmlsFromOneGitRepo.yml
  loop: "{{ roleXmlFilesToBeAppliedFromGit }}"
  loop_control:
    loop_var: roleXmlGitRepo
  tags:
    - always
