---
# Task to create one secret.
#####################################################################################
## Variables which must be set when invoking:
## secretApiKey: K8S API key
## secretApiHost: K8S API Host
## secretName: name of the secret
## secretNs: Namespace for the secret
## secretType: Secret type
## secretState: State of the secret (defaults to 'present')
## secretFiles: An entry of oscpSecrets.oscpGenericSecrets.secretFiles
#####################################################################################
- name: Create temporary file for templating YAML to apply for secret {{ secretName }}
  ansible.builtin.tempfile:
    state: file
    suffix: temp
  register: template_out
  tags:
    - always

- name: Create J2 template for secret {{ secretName }}
  ansible.builtin.template:
    src: ./secretData.j2
    dest: "{{ template_out.path }}"
  tags:
    - always

- name: Display created template for secret {{ secretName }}
  ansible.builtin.debug:
    msg: "Generated template is:\n\n{{ lookup('file', template_out.path) }}"
  tags:
    - hhueOnly

- name: Create the secret {{ secretName }}
  kubernetes.core.k8s:
    state: "{{ secretState }}"
    host: "{{ secretApiHost }}"
    api_key: "{{ secretApiKey }}"
    validate_certs: "no"
    src: "{{ template_out.path }}"
  tags:
    - always

- name: Cleanup generated template file for secret {{ secretName }}
  ansible.builtin.file:
    state: "absent"
    path: "{{ template_out.path }}"
  tags:
    - always
