---
# Task to create one secret.
#####################################################################################
## Variables which must be set when invoking:
## secretApiKey: K8S API key
## secretApiHost: K8S API Host
## secretName: name of the secret
## secretNs: Namespace for the secret
## secretType: Secret type
## secretState: State of the secret (defaults to 'present')
## secretFiles: An entry of oscpSecrets.oscpGenericSecrets.secretFiles
#####################################################################################
- name: Create secret
  block:
    - name: Create temporary file for templating YAML to apply for secret {{ secretName }}
      ansible.builtin.tempfile:
        state: file
        suffix: temp
      register: template_out

    - name: Create J2 template for secret {{ secretName }}
      ansible.builtin.template:
        src: ./secretData.j2
        dest: "{{ template_out.path }}"

    - name: Get remote template for secret {{ secretName }} using slurp
      ansible.builtin.slurp:
        src: "{{ template_out.path }}"
      register: slurpedFile

    - name: Display decoded slurp'ed data for secret {{ secretName }}
      ansible.builtin.debug:
        msg: "Slurped data decoded:\n\n{{ slurpedFile['content'] | b64decode }}"
      tags:
        - hhueOnly

    - name: Create the secret {{ secretName }}
      kubernetes.core.k8s:
        state: "{{ secretState }}"
        host: "{{ secretApiHost }}"
        api_key: "{{ secretApiKey }}"
        validate_certs: "no"
        src: "{{ template_out.path }}"

    - name: Cleanup generated template file for secret {{ secretName }}
      ansible.builtin.file:
        state: "absent"
        path: "{{ template_out.path }}"
  tags:
    - always
